; Title: My Beauty
; Description: This is beautiful. =)

(define (repeat k fn)
    (if (> k 0)
        (begin (fn) (repeat (- k 1) fn))
        nil))

(define (hexagon length)
  (color (rgb 1 1 0))
  (begin_fill)
    (pendown)
    (repeat 6 (lambda () 
                 (fd length)
                 (lt 60)))
    (penup)
  (end_fill))

(define (hexagons length levels)
    (hexagon length)
    (cond
        ((<= levels 1)
            nil)
        ((even? levels)
         (repeat 3 (lambda ()
                     (hexagons (/ length 2) (- levels 1))
                     (color "red")
                     (begin_fill)
                     (repeat 2 (lambda ()
                          (fd length)
                          (lt 60)))
                     (end_fill)
                     )))
        ((odd? levels)
         (repeat 3 (lambda ()
                     (hexagons (/ length 2) (- levels 1))
                     (color "blue")
                     (begin_fill)
                     (repeat 2 (lambda ()
                          (fd length)
                          (lt 60)))
                     (end_fill)
                     )))
        ))

(define (draw length levels)
    (bgcolor (rgb 1 1 0))
    (color (rgb 1 1 0))
    (setpos 200 400)
    (seth 180)
    (speed 10000)
    (hexagons length levels)
    (if (odd? levels) (color "red") (color "blue"))
    (rt 60)
    (bk (/ length 2))
    (rt 60)
    (bk (/ length 2))
    (begin_fill)
    (fd (/ length 2))
    (lt 60)
    (fd (/ length 2))
    (lt 60)
    (end_fill)
    )